package routes

import (
	"github.com/deanrock/cloud-door-mock-api/client"
	"github.com/deanrock/cloud-door-mock-api/utils"
	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

func InitAdminRoutes(e *echo.Echo) {
	admin := e.Group("/api/Admin")
	admin.Use(utils.RequiresAuthToken)

	admin.POST("/GetCurrent", func(c echo.Context) error {
		data := client.DoorCloudAdminDtosAdminBasicDto{
			AccessControlUserId: utils.Pointer(uuid.New()),
			Email:               utils.Pointer("user@example.com"),
			Id:                  utils.Pointer(uuid.New()),
			IsActivated:         utils.Pointer(true),
			IsTwoFactorEnabled:  utils.Pointer(false),
			Name:                utils.Pointer("Example User"),
			PermissionProfile: &client.DoorCloudPermissionDtosPermissionProfile{
				DefaultClientName: utils.Pointer("Company Inc."),
				IsUser:            utils.Pointer(true),
			},
			Permissions: utils.Pointer([]string{
				"DoorCloud.Web.Controllers.DataController.GetIncidentPriority",
				"DoorCloud.Web.Controllers.DataController.GetAccessPoints",
				"DoorCloud.Web.Controllers.LocationController.GetUserLocations",
				"DoorCloud.Web.Controllers.UserController.Get",
				"DoorCloud.Web.Controllers.UserController.GetAccessProfilesGridView",
				"DoorCloud.Web.Controllers.MenuController.Get",
				"DoorCloud.Web.Controllers.AdminController.GetCurrent",
				"DoorCloud.Web.Controllers.DataController.GetClients",
				"DoorCloud.Web.Controllers.ClientController.Get",
				"DoorCloud.Web.Controllers.DataController.GetCountries",
				"DoorCloud.Web.Controllers.IncidentController.GetGridView",
				"DoorCloud.Web.Controllers.ProviderController.SetServicePackage",
				"DoorCloud.Web.Controllers.UserAccessProfileController.GetGridView",
				"DoorCloud.Web.Controllers.UserController.SetPin",
				"DoorCloud.Web.Controllers.DataController.GetLanguages",
				"DoorCloud.Web.Controllers.AdminController.Get",
				"DoorCloud.Web.Controllers.AdminController.GetCheckedPermissionGroups",
				"DoorCloud.Web.Controllers.AdminController.AddRemoveClient",
				"DoorCloud.Web.Controllers.AccountController.SetPassword",
				"DoorCloud.Web.Controllers.IncidentController.Insert",
				"DoorCloud.Web.Controllers.DataController.GetAreas",
				"SystemPermissionType.AccessToClientsAdmins",
				"DoorCloud.Web.Controllers.AdminController.GetAllowedUnits",
				"DoorCloud.Web.Controllers.AdminController.GetDisallowedUnits",
				"DoorCloud.Web.Controllers.AccessLogController.GetGridView",
				"DoorCloud.Web.Controllers.DataController.GetIncidentAdminGroups",
				"DoorCloud.Web.Controllers.IncidentController.Get",
				"DoorCloud.Web.Controllers.IncidentReplyController.GetAll",
				"DoorCloud.Web.Controllers.IncidentReplyController.Insert",
				"DoorCloud.Web.Controllers.IncidentController.GetAllReplies",
				"DoorCloud.Web.Controllers.IncidentController.InsertReply",
				"DoorCloud.Web.Controllers.IncidentController.SendToEmail",
				"DoorCloud.Web.Controllers.IncidentController.AssignAdmin",
				"DoorCloud.Web.Controllers.IncidentController.SetPriority",
				"DoorCloud.Web.Controllers.IncidentController.SetAdminGroup",
				"DoorCloud.Web.Controllers.IncidentController.SetStatus",
				"DoorCloud.Web.Controllers.DataController.GetIncidentAdmins",
				"DoorCloud.Web.Controllers.IncidentController.GetStatistics",
				"DoorCloud.Web.Controllers.DataController.GetOutputStatuses",
				"DoorCloud.Web.Controllers.IncidentController.Delete",
				"DoorCloud.Web.Controllers.AccessLogController.GetUsersActivity",
				"SystemPermissionType.IsUser",
				"DoorCloud.Web.Controllers.DataController.GetControllersByClient",
				"DoorCloud.Web.Controllers.DataController.GetAreasByClient",
				"DoorCloud.Web.Controllers.GettingStartedController.Get",
				"DoorCloud.Web.Controllers.GlossaryController.Get",
				"DoorCloud.Web.ChangeLog",
				"DoorCloud.Web.Controllers.DataController.GetIncidentAdminGroupsByClient",
				"DoorCloud.Web.Controllers.ManualController.GetAll",
				"DoorCloud.Web.Controllers.ManualController.GetPreSignedLink",
				"DoorCloud.Web.Controllers.OutputController.AddOutputToAdminFavorite",
				"DoorCloud.Web.Controllers.OutputController.RemoveOutputFromAdminFavorite",
				"DoorCloud.Web.Controllers.AdminController.Disable2FA",
				"DoorCloud.Web.Controllers.AdminController.Enable2FA",
				"DoorCloud.Web.Controllers.AdminController.GetFullDataByUserId",
				"DoorCloud.Web.Controllers.UserContactController.Get",
				"DoorCloud.Web.Controllers.UserController.RemovePin",
				"DoorCloud.Web.Controllers.UserController.DeleteProfilePhoto",
				"DoorCloud.Web.Controllers.UserController.GetProfilePhoto",
				"DoorCloud.Web.Controllers.UserController.UploadProfilePhoto",
				"DoorCloud.Web.Controllers.AccessPointController.AddToFavorites",
				"DoorCloud.Web.Controllers.AccessPointController.RemoveFromFavorites",
				"DoorCloud.Web.Controllers.ReportController.RenderReport",
				"DoorCloud.Web.Controllers.AuditLogController.AuditClientSideExport",
				"DoorCloud.Web.Controllers.UserDeviceController.Get",
				"DoorCloud.Web.Controllers.UserDeviceController.GetAll",
				"DoorCloud.Web.Controllers.UserDeviceController.Register",
				"DoorCloud.Web.Controllers.UserDeviceController.IsDeviceRegistered",
				"DoorCloud.Web.Controllers.EventLogController.GetAll",
				"DoorCloud.Web.Controllers.EventLogController.GetDirections",
				"DoorCloud.Web.Controllers.EventLogController.GetEventLogStatuses",
				"DoorCloud.Web.Controllers.EventLogController.GetGraphDataPoints",
				"DoorCloud.Web.Controllers.EventLogController.GetOrigins",
				"DoorCloud.Web.Controllers.AccessPointController.GetAllDoorsWithBleReaders",
				"DoorCloud.Web.Controllers.UserController.GetMobileAccessCredentialsToken",
				"DoorCloud.Web.Controllers.AccountController.SendResetPasswordEmail",
				"DoorCloud.Web.Controllers.UserController.GetAllAccessProfiles",
				"DoorCloud.Web.Controllers.EventLogController.GetEventReasons",
				"DoorCloud.Web.Controllers.EventLogController.GetEventResults",
				"DoorCloud.Web.Controllers.EventLogController.GetEventTypes",
				"DoorCloud.Web.Controllers.AdminController.GetNotificationSubscriptions",
				"DoorCloud.Web.Controllers.NotificationSubscriptionController.MuteNotificationChannel",
				"DoorCloud.Web.Controllers.NotificationSubscriptionController.ProcessFcmToken",
				"DoorCloud.Web.Controllers.NotificationSubscriptionController.UnmuteNotificationChannel",
				"DoorCloud.Web.Controllers.AdminController.GetAdmins",
				"DoorCloud.Web.Controllers.ControllerController.GetControllerActivationStatuses",
				"DoorCloud.Web.Controllers.AlarmController.GetAlarmGroups",
				"DoorCloud.Web.Controllers.OutputController.GetRelayTypes",
				"DoorCloud.Web.Controllers.IncidentController.GetIncidentPriority",
				"DoorCloud.Web.Controllers.InputController.GetInputDefaultStates",
				"DoorCloud.Web.Controllers.ControllerController.GetControllerOnlineStatuses",
				"DoorCloud.Web.Controllers.LocationController.OpenDoorOnLocation",
				"DoorCloud.Web.Controllers.CommandLogController.GetCommandStatus",
				"DoorCloud.Web.Controllers.LocationController.OpenAccessPointWithNfc",
				"SystemPermissionType.MobileAccess",
			}),
			Title:    utils.Pointer("Example User"),
			UserId:   utils.Pointer(uuid.New()),
			Username: utils.Pointer("user@example.com"),
		}

		return c.JSON(200, utils.ToAbpResponse(data))
	})
}
